allowBuilds:
  esbuild: true

minimumReleaseAge: 10080 # 7 days
blockExoticSubdeps: true # no git branch as package url
minimumReleaseAgeExclude:
  - "@oxfmt/binding-android-arm-eabi"
  - "@types/node"
  - "react"
  - "react-dom"
  - "oxlint@1.70.0"
  - "@oxlint/binding-*"

resolutionMode: highest

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux
    - win32
