allowBuilds:
  esbuild: true

minimumReleaseAge: 10080 # 7 days
blockExoticSubdeps: true # no git branch as package url
minimumReleaseAgeExclude:
  - "@oxfmt/binding-android-arm-eabi"
  - "@types/react"
  - "@types/react-dom"
  - "@types/node"
  - "react"
  - "react-dom"

resolutionMode: highest

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux
    - win32
